config/routes.rb
Rails.application.routes.draw do
  root to: "days#today"
  get "/all", to: "days#index", as: :all_days
  get "/required-learning", to: "activities#index", as: :required_learning
  post "/activities/:activity_id/links", to: "links#create", as: :activity_links
  resources :days, path: "/" do
    resources :activities, only: [:edit, :create, :update, :destroy, :index]
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :day
  has_many :links
  has_paper_trail
  validates :start, :end, :body, presence: true
  scope :by_start, -> { order(start: :asc) }
  scope :required, -> { where(required_learning: true) }
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model

    mapping do
      # ...
    end

    # def self.search(query)
    #   # ...
    # end
  end
end

# In: app/models/article.rb
#

app/models/day.rb
require 'active_support/core_ext/integer/inflections'

class Day < ActiveRecord::Base
  has_paper_trail
  validates :date, uniqueness: true, presence: true
  has_many :activities, -> { order "start asc" }

  def yesterday
    param_date date - 1
  end

  def tomorrow
    param_date date + 1
  end

  def to_param
    param_date date
  end

  def param_date(date)
    "#{date.strftime("%B")}-#{date.day.ordinalize}-#{date.year}"
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :find_day, except: :index

  def index
    @activities = Activity.required.includes(:day).order("days.date asc, start")
  end

  def create
    @activity = @day.activities.create(params.require(:activity).permit!)
    if @activity.save
      redirect_to @day
    else
      render "/days/show"
    end
  end

  def edit
    @activity = Activity.find params[:id]
  end
  def update
    @activity = @day.activities.find(params[:id])
    if @activity.update(params.require(:activity).permit!)
      redirect_to edit_day_path(@day)
    else
      render "days/edit"
    end
  end

  def destroy
    @activity = @day.activities.find(params[:id])
    @activity.destroy
    redirect_to @day
  end
  private

  def find_day
    date = Date.parse(params[:day_id].remove("-"))
    @day = Day.find_by(date: date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :find_day, only: [:show, :edit, :update]
  def index
    @days = Day.order("date asc").includes(:activities)
  end

  def show
    @day ||= Day.new(date: @date)
  end

  def today
    @day = Day.find_or_initialize_by(date: Date.today)
    render :show
  end

  def new
    @day = Day.new(date: params[:date])
  end

  def create
    @day = Day.new(params.require(:day).permit!)
    if @day.save
      redirect_to @day
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @day.update(params.require(:day).permit(:body))
      redirect_to @day
    else
      render :edit
    end
  end

  private

  def find_day
    @date = Date.parse(params[:id].remove("-"))
    @day = Day.find_by(date: @date)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def create
    @activity = Activity.find(params[:activity_id])
    @activity.links.new(params.require(:link).permit!)
    if @activity.save
      redirect_to @activity.day
    else
      render "activity/edit"
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(MarkdownPygments,
      fenced_code_blocks: true,
      autolink: true,
      tables: true)
    markdown.render(text).html_safe
  end
end

app/helpers/days_helper.rb
module DaysHelper
  def date_to_s(date)
    "#{date.strftime('%A %B')} #{date.day.ordinalize}, #{date.year}"
  end

  def date_class(day)
    if day.past?
      "past"
    elsif day.today?
      "today"
    else
      "future"
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/activities/_form.html.erb
<%= form_for [day, activity] do |f| %>
  <%= f.hidden_field :day_id, value: day.id %>
  <div class='form-group'>
    <%= f.datetime_select :start, minute_step: 5, ampm: true, start_hour: 8, end_hour: 22 %>
    <%= f.label :end, "-" %>
    <%= f.datetime_select :end, minute_step: 5, ampm: true, start_hour: 8, end_hour: 22 %>
  </div>
  <div class='form-group'>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>
  <div class='form-group'>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class='form-group'>
    <%= f.label :required_learning do %>
      <%= f.check_box :required_learning %>
      Required Learning
    <% end %>
  </div>
  <%= f.submit %>
<% end %>

app/views/activities/edit.html.erb
<h1>Edit Activity</h1>

<%= form_for [@activity, Link.new] do |f| %>
  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.url_field :url %>
  </div>
  <%= f.submit %>
<% end %>

app/views/activities/index.html.erb
<%= link_to "<i class='fa fa-calendar'></i>".html_safe, all_days_path, class: "pull-center" %>
<h1>Required Learning</h1>

<ul>
  <% @activities.each do |act| %>
    <li>
      <input type='checkbox' />
      <%= link_to_if act.url.present?,  act.body, act.url %>
      <small class='muted'> | <%= link_to date_to_s(act.day.date), act.day %></small>
    </li>
  <% end %>
</ul>

app/views/activities/new.html.erb
<h1>Create a new Activity!</h1>
<%= render 'form' %>

app/views/days/_form.html.erb
<%= form_for @day do |f| %>
  <% if @day.new_record? %>
    <div class="form-group">
      <%= f.label :date %>
      <%= f.text_field :date, class: "date-picker" %>
    </div>
  <% end %>
  <div class='form-group'>
    <%= f.label :body, "Markdown" %>
    <%= f.text_area :body %>
  </div>

  <%= f.submit %>
<% end %>

app/views/days/edit.html.erb
<h1>
  Edit
  <%= link_to @day do %>
    <%= @day.date.strftime("%B") %>
    <%= @day.date.day.ordinalize %>, <%= @day.date.year %>
  <% end %>
</h1>
<%= render "days/form" %>

<div class='schedule'>
  <h2 class='title'>
    Schedule
    <%= link_to "+", "#", class: "show pull-right", data: {target: ".new-schedule"} %>
  </h2>
  <% @day.activities.by_start.each do |act| %>
    <%= render "activities/form", day: @day, activity: act %>
    <%= link_to "<i class='fa fa-trash'></i>".html_safe, [@day, act], method: :delete, data: {confirm: "Are you sure?" } %>
    <%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_day_activity_path(@day, act) %>
  <% end %>
</div>

app/views/days/home.html.erb
<div class="col-md-12">
 <div class="row">
   <h1>Today's Lesson</h1>
   <br>
     <div class="search">
         <%=  form_tag days_path, class: "form-inline", method: :get do %>
         <%= text_field_tag :query, params[:query], class: "form-control" %>
         <%= submit_tag "Search", class: "btn btn-primary" %>
         <% if params[:query].present? %>
         <%= link_to "clear", root_path %>
         <% end %>
       <% end %>
     </div>

     <div class="front-page">
       <% @days.each do |day| %>
       <% if day.date == Date.today %>
         <h1><%= day.date.strftime("%m/%d/%Y") %></h1>
         <h1><%= day.url %></h1>
         <p><%= markdown(day.description) %></p>
     </div>

       <div class="activities-row">
         <h1>Schedule</h1>
         <% day.activities.each do |activity| %>
           <p>
             <%= activity.start_time.strftime("%l%P") %> - <%= activity.end_time.strftime("%l%P") %>

             <%= link_to nil, "http://#{activity.url}" %>
           </p>
         <% end %>
       </div>
     <% end %>
    <% end %>
   </div>
  </div>

    <div class="col-md-12">
     <div class="row">
      <h1> <%= link_to "Add a new lesson", new_day_path  %> </h1>
      <h1> <%= link_to "View other lessons", days_path(@days) %>
     </div>
    </div>
  </div>

app/views/days/index.html.erb
<section class='days'>
  <%= link_to "View all required learning", required_learning_path, class: "pull-right btn" %>
  <%= link_to "+ Add day", new_day_path, class: "pull-right btn" %>
  <h1>Schedule</h1>
    <% @days.each do |day| %>
      <article class="day-preview <%= date_class day.date %>">
        <div class='small-date'><%= link_to date_to_s(day.date), day %></div>
        <div class='summary'>
          <table>
            <% day.activities.by_start.each do |act| %>
              <tr>
                <td width="120px"><%= act.start.strftime("%l:%M %p") %></td>
                <td width="120px"><%= act.end.strftime("%l:%M %p") %></td>
                <td><%= link_to_if act.url.present?, act.body, act.url %></td>
              </tr>
            <% end %>
          </table>
        </div>
      </article>
    <% end %>
  <hr/>
</section>

app/views/days/new.html.erb
<%= render "form" %>

app/views/days/show.html.erb
<div class='controls'>
  <%= link_to "<i class='fa fa-arrow-left'></i> Yesterday".html_safe, day_path(@day.yesterday), class: "pull-left" %>
  <%= link_to "Tomorrow <i class='fa fa-arrow-right'></i>".html_safe, day_path(@day.tomorrow), class: "pull-right" %>
  <%= link_to "<i class='fa fa-calendar'></i>".html_safe, all_days_path, class: "pull-center" %>
</div>
<article class='day'>
  <div class='body'>
    <h1 class='muted'>
      <%= date_to_s @day.date %>
      <small style='font-size: 28px;' class='muted'></small>
    </h1>

    <% if @day.persisted? %>
      <%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_day_path(@day), class: "pull-right" %>
      <div>
        <%= markdown @day.body %>
      </div>
      <div class='schedule'>
        <h2 class='title'>
          Schedule
          <%= link_to "<i class='fa fa-plus'></i>".html_safe, "#", class: "show pull-right", data: {target: ".new-schedule"} %>
        </h2>
        <table>
          <% @day.activities.each do |act| %>
            <tr class='<%= "required-learning" if act.required_learning? %>'>
              <td width="120px"><%= act.start.strftime("%l:%M %p") %></td>
              <td width="120px"><%= act.end.strftime("%l:%M %p") %></td>
              <td>
                <%= link_to_if act.url.present?, act.body, act.url %>
                <% act.links.each do |link| %>
                  <%= link_to link.text, link.url %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class='new-schedule hide'>
        <%= render "activities/form", day: @day, activity: Activity.new(start: @day.date, end: @day.date) %>
      </div>
    <% else %>
      <%= link_to "<i class='fa fa-pencil'></i>".html_safe, new_day_path(date: @day.date), class: "pull-right" %>
      <div class="alert alert-notice">
        <h2 class='muted'>Nothing for this day yet...</h2>
      </div>
    <% end %>

  </div>
</article>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Oops there were some errors. Please try again:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CbCalendar</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='main' role='main'>
  <%= yield %>
</div>
</body>
</html>